name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.8
authors:
  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.10.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  open_iconic_flutter: any
  wakelock: any
  flutter_widgets: any
  pedantic: any
  meta: any
  flutter_widget_from_html_core: any
  music_volume: any
  screen: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
